# Generated by Django 3.2 on 2021-04-25 10:23

import Accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('RegistrationID', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('CustomPassword', models.CharField(max_length=200)),
                ('ProfilePicture', models.ImageField(default=Accounts.models.get_default_profile_image, upload_to=Accounts.models.get_profile_image_filepath)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('DateOfBirth', models.DateField(default=django.utils.timezone.now)),
                ('UserType', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Alumni', 'Alumni')], max_length=10)),
                ('Description', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
