# Generated by Django 3.2 on 2021-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Description',
            field=models.CharField(max_length=40),
        ),
    ]
