# Generated by Django 3.2 on 2021-04-25 11:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=300)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('TimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('TimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='AnswerLikes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='Forum.question')),
            ],
        ),
    ]
